### ISSUE TITLE
sshWorkerFakeVmPasswordTest false positive; too strict on valid output

### ISSUE THREAD

**Issue by jeffpeiyt** [eBay/parallec#10]
Found by Lukasz

currently it is too strict on the expected oup; probably sometimes the error output is slightly different. you can rerun just this test, and then print the output, we will know the other error string.

https://github.com/eBay/parallec/blob/master/src/test/java/io/parallec/core/main/ssh/ParallelClientSshTest.java#L32

**Comment by kryger** [comment]
I'm glad I could help, even if unwittingly :)

**Comment by jeffpeiyt** [comment]
Cannot reproduce it in Travis CI or my local.. will reopen if needed
