### ISSUE TITLE
is it suitable for android?

### ISSUE THREAD

**Issue by snowdream** [eBay/parallec#17]
is it suitable for android?

**Comment by jeffpeiyt** [comment]
we have not tested on Android. 
We could replace the HTTP client from AHC to https://github.com/loopj/android-async-http 
BTW is there use case where we need to send a lot of parallel requests from a phone?

**Comment by snowdream** [comment]
may be.

**Comment by jeffpeiyt** [comment]
@snowdream , could you please give a specific use case on this? just curious about what type of application :-)

Parallec intends for large amount of concurrent API calls. wonder if a lot of concurrent requests from the phone drain the battery. Have not worked on android much.

**Comment by snowdream** [comment]
for example, app about stock.
it will get the data every several seconds.

**Comment by jeffpeiyt** [comment]
thanks Snowdream, will you need to call a lot of APIs at the same time? Can you try if this works on Android? we need to check Akka library with Android too

**Comment by snowdream** [comment]
sorry. i have not met these.
