### ISSUE TITLE
Scala version

### ISSUE THREAD

**Issue by darienmt** [eBay/parallec#18]
This is a very interesting library. I am interested on creating a Scala version of it. 
How can I start the migration?
Is anybody else interested?

**Comment by jeffpeiyt** [comment]
@darienmt ,

thanks for your interests.  Yes  you can build it with scala akka.


Also suggest you check out http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/http/client-side/index.html

and see if you can build features of Parallec on top of this: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/http/client-side/index.html

From my understanding, the Akka HTTP client is still WIP and building up features.   Maybe you can suggest it and contribute features in Parallec in it.

thanks,

**Comment by darienmt** [comment]
Akka HTTP is a WIP, but it is better to start using sooner than later. Flows bring another abstraction level on top of actors. It is a great suggestion. 
I already update my fork from your repo. Should I branch off from master or dev on my fork?

**Comment by jeffpeiyt** [comment]
yes. please branch from master :-)

**Comment by jeffpeiyt** [comment]
Close it now as there is no updates. If needed we can reopen it
