### ISSUE TITLE
Test Senario

### ISSUE THREAD

**Issue by nicqchen01** [eBay/parallec#19]
there are some question about your test evidence,

1. what is your test environment setting?
2. just a simple call ? could you help get more test detail about request /responce size?

**Comment by jeffpeiyt** [comment]
Hi NicqChen,

thanks for the interests. do you mean the unit tests for coverages or those 12 seconds 8,000 servers demo?

for the 8000 servers 12/16 seconds demo, those are uniform HTTPS GET call request ; request very small string  /XX;   response typically less than 1KB


feel free to conduct performance testing in your environment, as the results varies based on network speed, response time, the slowest servers, timeout settings

**Comment by jeffpeiyt** [comment]
hope this answer is good @nicqchen01 , please let me know if you have more questions

**Comment by jeffpeiyt** [comment]
as the question is answered, close the issue now
