### ISSUE TITLE
Untrusted https

### ISSUE THREAD

**Issue by marfago** [eBay/parallec#36]
How is it possible to handle untrusted https?

**Comment by jeffpeiyt** [comment]
Thanks @marfago for your interests in Parallec.

Do you mean to run sth like ignoring server cert  (like [curl -k](http://unix.stackexchange.com/questions/60750/does-curl-have-a-no-check-certificate-option-like-wget))?

As parallec is using [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client) for http request, and we support setting customized [AsyncHttpClient](http://static.javadoc.io/com.ning/async-http-client/1.6.5/com/ning/http/client/AsyncHttpClient.html#AsyncHttpClient) object as the one for sending request. You may supply your own AsyncHttpClient with your own sslContext and timeout etc to ignore the untrusted cert .You may follow doc [here](http://www.parallec.io/docs/submit-task/#apis-on-http) with a parameter of `setAsyncHttpClient()`

[Here](https://github.com/eBay/parallec-plugins/blob/master/parallec-clientauth/src/main/java/io/parallec/plugin/http/clientauth/HttpClientFactoryClientAuth.java) and [here](https://github.com/eBay/parallec-plugins/blob/master/parallec-clientauth/src/main/java/io/parallec/plugin/http/clientauth/ClientAuthAdaptor.java) are some example to enable HTTPS Client Auth by supplying our customized AsyncHttpClient object with a much more complex ssl context.  

[Here](http://stackoverflow.com/questions/2642777/trusting-all-certificates-using-httpclient-over-https) is some example to build a SSL context which trusts all cert.


Some code to set the customized client and use it in all the sessions of this pc
```
        if (factory == null) {
            factory = new HttpClientFactoryClientAuth(privKeyPasshraseFilePath,
                    keystoreFilePath, algorithm, verifyServerCert);
        } else {
            logger.debug("factory is already initialized. will NO OP. "
                    + "call reset() to close the current clients and then try again.");
            return;
        }
        pc.setCustomClientFast(factory.getFastClient());
        pc.setCustomClientSlow(factory.getSlowClient());
        pc.setHttpClientTypeCurrentDefault(HttpClientType.CUSTOM_FAST);
```

**Comment by marfago** [comment]
Thank you.
