### ISSUE TITLE
Follow 301 redirects

### ISSUE THREAD

**Issue by brunoribeiro** [eBay/parallec#43]
Are follow redirects disabled by default? Is there any config switch to enable redirects? 

I know that in ning async-http-client I can use the RequestBuilder .setFollowRedirects(boolean), but could not find anything similar in parallec.

**Comment by jeffpeiyt** [comment]
@brunoribeiro  

Parallec supports [supplying](http://www.parallec.io/javadoc/io/parallec/core/ParallelTaskBuilder.html#setAsyncHttpClient-com.ning.http.client.AsyncHttpClient-) your own customized AsyncHttpClient object: http://www.parallec.io/docs/submit-task/#apis-on-http  where you can set any config with it.

However, seems https://github.com/AsyncHttpClient/async-http-client/issues/788 mentioned the older version if AHC has bugs in this config even if it set as true

**Comment by brunoribeiro** [comment]
Understood, I am going to configure an  AsyncHttpClient to follows redirects, and test my use cases.

**Comment by jeffpeiyt** [comment]
@brunoribeiro  BTW, #37  has details of the parallec with AHC upgraded to the latest version 2.0.15 (requires JDK8) it has not been tested in production but passed all the comprehensive tests.

**Comment by brunoribeiro** [comment]
@jeffpeiyt great, I will test it as soon as I can.
