### ISSUE TITLE
ParallelClient responseContent enconding

### ISSUE THREAD

**Issue by jeffpeiyt** [eBay/parallec#46]
Issue raised in https://groups.google.com/forum/#!topic/parallec/MB2QyGGnwTk

Need to add a parameter in http meta to get the response body with the proper encoding.

`public String getResponseBody(String charset) throws IOException;`
`response.getResponseBody("UTF-8")`

**Comment by jeffpeiyt** [comment]
Customer indicates he is working on patching this. Close it for now and may reopen it if need further action

**Comment by devnewton** [comment]
Any news on this issue? Encoding bug makes parallec unusable for production.

**Comment by jeffpeiyt** [comment]
@devnewton  busy recently but should get it in 1 week. 
It is better to pass a parameter per task but setting a global one would be super easy.

https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/Response.html#getResponseBody(java.lang.String)

Need to add a parameter in http meta to get the response body with the proper encoding.

public String getResponseBody(String charset) throws IOException;
response.getResponseBody("UTF-8")

**Comment by jeffpeiyt** [comment]
@devnewton  please check tests on none-unicode websites:

https://github.com/eBay/parallec/blob/930fc4d897cd4cc414799af917b9dafb8ccaf70a/src/test/java/io/parallec/core/main/http/ParallelClientHttpBasicMoreOptionsTest.java#L119

https://github.com/eBay/parallec/blob/master/CHANGELOG.md#version-0106

**Comment by devnewton** [comment]
Thanks!

**Comment by jeffpeiyt** [comment]
Released 0.10.6
