### ISSUE TITLE
can i post one site multi times?

### ISSUE THREAD

**Issue by coolmenu** [eBay/parallec#52]
I test in setTargetHostFromString("localhost localhost .... ")
but i get one result

I want to send post api to my api server from a queue,so i want parralec post, how can i do ?
thanks

**Comment by jeffpeiyt** [comment]
Hi @coolmenu , thanks for trying parallec.

You may follow example here http://www.parallec.io/docs/submit-task/#apis-on-variable-replacement-for-heterogeneous-requests  for diff req to the same server. 

Currently the parameters for different calls may need to be different.  You could add a dummy var in the header part to make different API calls look different, even those these dummy headers may not have any real impact

https://github.com/eBay/parallec-samples/blob/master/sample-apps/src/main/java/io/parallec/sample/app/http/HttpDiffRequestsSameServerApp.java

**Comment by coolmenu** [comment]
thanks for replay
but my api endpoint is a post json method curl -X -POST http://localhost:9999/api/actives -d '{"message": "123"} like this
how can i replace bodyentities in setHttpEntityBody?

**Comment by jeffpeiyt** [comment]
@coolmenu  just the same way as long as you put a $VAR in the setHttpEntityBody, and follow the same format , it will be replaced.  parallec will seek $XX  in the body url, header etc and replace as in the pair

**Comment by coolmenu** [comment]
Thanks a lot!very charm!

发自我的 iPhone
