### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by hackeys** [eBay/parallec#55]
Hi Team ,

First of all , i would like to thank you from bottom of my heart for such a great piece of code .

I would like to request a feature to support telnet and nmap features as part of this .

Thank you again .

**Comment by jeffpeiyt** [comment]
@hackeys  Thanks so much for your kind encouragement! 

I am not expert on Telnet but seems it is very close to raw TCP connections: https://en.wikipedia.org/wiki/Telnet#Telnet_data  .  Could you try with parallel TCP?

For nmap, seems it is similar to Parallec as a scanner designed to target large amount of targets: https://nmap.org/book/man.html   However it is less generic and focuses on a particular use cases.  I suppose we can use existing parallelc features to implement functions similar to nmap.

**Comment by jeffpeiyt** [comment]
Will close the ticket for now if there is no more questions. Feel free to reopen it
