### ISSUE TITLE
How to use it on Android?

### ISSUE THREAD

**Issue by lnpusong123** [eBay/parallec#58]
I want to know how use it on Android. When i add dependency,gradle build with some warings.
And i can't run it on my phone.

**Comment by jeffpeiyt** [comment]
@lnpusong123 thanks for the interests. I believe there is some trickiness of using Akka with Android after some google search.  Not sure if it is well supported by default
http://www.lightbend.com/activator/template/macroid-akka-pingpong
https://spin.atomicobject.com/2013/06/20/akka-scala-on-android/

**Comment by jeffpeiyt** [comment]
closed for now for no more activity.
