### ISSUE TITLE
How to send get request for the list of urls....

### ISSUE THREAD

**Issue by satheessh** [eBay/parallec#59]
I have below urls in the array list.   How to sent get request  to all of the urls...

http://www.parallec.io/docs/track-status/
https://stackoverflow.com/questions/3142915/how-do-you-create-an-asynchronous-http-request-in-java

**Comment by jeffpeiyt** [comment]
Hi @satheessh 

Thanks for trying Parallec! For these 2 urls on parallec.io and stackoverflow.com, I assume they belong to the category of "Different requests to different target hosts"

Could you please follow
http://www.parallec.io/docs/submit-task/#apis-on-variable-replacement-for-heterogeneous-requests

https://github.com/eBay/parallec-samples/blob/master/sample-apps/src/main/java/io/parallec/sample/app/http/HttpDiffRequestsDiffServersApp.java

thanks,

**Comment by jeffpeiyt** [comment]
close it for now
