### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by 1ab1** [eBay/parallec#61]
Any plans for adding http(s) proxy support?

**Comment by jeffpeiyt** [comment]
Parallec can use customized async http client, which supports proxy: https://github.com/AsyncHttpClient/async-http-client/blob/master/README.md#configuration

http://www.parallec.io/docs/configurations/#async-http-client

Could you please try this out?

**Comment by 1ab1** [comment]
@jeffpeiyt  Thank you. 
```
com.ning.http.client.AsyncHttpClientConfig clientConfig =  new com.ning.http.client.AsyncHttpClientConfig.Builder().setProxyServer(new com.ning.http.client.ProxyServer("127.0.0.1", 8080)).build();
com.ning.http.client.AsyncHttpClient client = new AsyncHttpClient(clientConfig);
```
