### ISSUE TITLE
Unix network commands executing.

### ISSUE THREAD

**Issue by maystrovyy** [eBay/parallec#62]
Hi, at the first - thank you for this cool project!
I have a question, could I execute host or nslookup commands from prepareTcp/prepareUdp methods?
If yes - please, reproduce it.

**Comment by jeffpeiyt** [comment]
@maystrovyy  thank you for the interests in Parallec!

You can run those command via the parallel ssh option and run any scripts/commands there. 

thanks,

**Comment by maystrovyy** [comment]
@jeffpeiyt thank you, I'll try it.

**Comment by maystrovyy** [comment]
Cool, I got it right! But one question: 
`ParallelTask task = pc.prepareSsh().setConcurrency(1500)
                .setTargetHostsFromString("localhost")
                .setSshLoginType(SshLoginType.PASSWORD)
                .setSshUserName("root")
                .setSshPassword("pass")
                .setSshCommandLine("host google.com; host gmail.com; ")
                .execute((res, resContext) -> System.out.println(res.getResponseContent()));`
sout's 2 results, but when I try to get:
`Map<String, NodeReqResponse> result = task.getParallelTaskResult();` - there are only 1 result without any info of "res.getResponseContent()".
Could you help me?

**Comment by jeffpeiyt** [comment]
@maystrovyy . Glad you make some progress :-) .   Sometimes it means the destination host can get stuck (where the socket is connected by no response back etc)   can you first try a quick command such as `ls` with a single target host and make sure the machine is ssh able ? 

Then try with more target hosts; the timeout can be changed if you try to run a script that takes very long time to return. http://www.parallec.io/docs/configurations/#timeout

**Comment by jeffpeiyt** [comment]
Closing it for now as there is no more activity. Feel free to reopen it.

**Comment by maystrovyy** [comment]
Hi, what about keeping connection with SSH, for example, I need to execute 2 list of commands in parallel, could I have connected ParallelClient and then just execute it, such as:
````
ParallelClient pc = new ParallelClient();

pc.prepareSsh()
 .setConcurrency(400)
 .setTargetHostsFromString("localhost")
 .setSshLoginType(SshLoginType.PASSWORD)
 .setSshUserName("root")
 .setSshPassword("pass");

pc.initialize();

task1.execute(pc, commands1);
task2.execute(pc, commands2);
````

Execute method in tasks are something like this:

````
pc.prepareSsh()
  .setSshCommandLine(commands)
  .execute((response, map) -> ... );
pc.releaseExternalResources();
````

Thanks.
