### ISSUE TITLE
Keeping active SSH connection

### ISSUE THREAD

**Issue by maystrovyy** [eBay/parallec#65]
Hi, what about keeping connection with SSH, for example, I need to execute 2 list of commands in parallel, could I have connected ParallelClient and then just execute it, such as:
````
ParallelClient pc = new ParallelClient();

pc.prepareSsh()
 .setConcurrency(400)
 .setTargetHostsFromString("localhost")
 .setSshLoginType(SshLoginType.PASSWORD)
 .setSshUserName("root")
 .setSshPassword("pass");

pc.initialize();

task1.execute(pc, commands1);
task2.execute(pc, commands2);
````

Execute method in tasks are something like this:

````
pc.prepareSsh()
  .setSshCommandLine(commands)
  .execute((response, map) -> ... );
pc.releaseExternalResources();
````

Thanks.

**Comment by maystrovyy** [comment]
A little bit researching the documentation and realized that I need `SshProvider`, right?

**Comment by jeffpeiyt** [comment]
will check about it later today

**Comment by maystrovyy** [comment]
Thank you, waiting for answer

**Comment by jeffpeiyt** [comment]
@maystrovyy  thanks for the kind patience.

1. please check http://www.parallec.io/docs/api-overview/#when-to-release-resources  and you do not need to `releaseExternalResources ()` every time. 

2.  Can you explain more about `Upd: I tried by changing setCommandLine in SshMeta, but the execution process is very long.` ?    this is just like a parallel ssh to execute commands or scripts. As long as the scripts are quick to finish, it will finish quickly.  If you do not care about the output you can run in the background with `&` and poll the results later.

**Comment by maystrovyy** [comment]
I have 2 string commands (with & between every command), for example:
````
String commands1 = "echo test2 & echo test & ...";
String commands2 = "echo test2 & echo test2 & ...
````
Length of this strings is optimal to avoid actor's timeout. So the next step is: 
````
Stream.of(commands1, commands2).parellelStream()
   .forEach(commands -> {
        sshMeta.setCommandLine(commands);
        sshProvider.executeSshCommand().getResponseBody());
}
````
And add the result to the StringBuilder.

**Comment by maystrovyy** [comment]
Why I have this exception:
```
If exection is JSchException: Auth cancel and using public key. 
Make sure 1. private key full path is right (try sshMeta.getPrivKeyAbsPath()). 
2. the user name and key matches  com.jcraft.jsch.JSchException: connection is closed by foreign host
```
My SSH connection is:
```
pc.prepareSsh()
                .setConcurrency(400)
                .setConfig(this.config)
                .setTargetHostsFromString("localhost")
                .setSshLoginType(SshLoginType.PASSWORD)
                .setSshUserName("username")
                .setSshPassword("pass")
                .setSshCommandLine(commands)
                .execute((response, map) -> builder.append(response.getResponseContent()));
```

**Comment by jeffpeiyt** [comment]
@maystrovyy  could you compare your code with this example? https://github.com/eBay/parallec-samples/blob/master/sample-apps/src/main/java/io/parallec/sample/app/ssh/SshApp.java  ?

**Comment by maystrovyy** [comment]
@jeffpeiyt The same of password authentication.

**Comment by jeffpeiyt** [comment]
@maystrovyy  looks like an auth issue. Could you please change a host / user/ password and validate them with real ssh sessions first? 

also remove this `.setConfig(this.config)` or try use the sample code with the right user/pass?

**Comment by maystrovyy** [comment]
Credentials are correct, what is the difference to connect on localhost or dedicated host. 
Config is simple `ParallelTaskConfig` with `setActorMaxOperationTimeoutSec(20);`
This exception doesn't happen often, so the connection should be normal.

**Comment by jeffpeiyt** [comment]
@maystrovyy  Thanks. Do you mean it is not stable? BTW for SSH the max concurrency may be around 200. Can you try lower the concurrency to say 20 and if it is still there?

**Comment by maystrovyy** [comment]
@jeffpeiyt thank you for the answer, I'll try it tonight.
