### ISSUE TITLE
Tasks keep running

### ISSUE THREAD

**Issue by harjitdotsingh** [eBay/parallec#66]
Hi there,

When I submit a task, It keeps running. I just want to run it once when or on demand ? Is there any way to do that ?

**Comment by jeffpeiyt** [comment]
@harjitdotsingh thanks for trying parallec.

It should run once.  Could you please paste your code here or print some debugging information?

Could you please check the samples here and compare with your code? 
https://github.com/eBay/parallec-samples

**Comment by harjitdotsingh** [comment]
Here is the code


`ParallelTask pt = parallelClient.prepareHttpGet("/search/query?q=$QUERY")
                .setHttpHeaders(new ParallecHeader().addPair("x-user", env.getProperty("ifi.user")).addPair("x-password", env.getProperty("ifi.password"))).setProtocol(RequestProtocol.HTTPS)
                .setHttpPort(443)
                .async()
                .setReplaceVarMapToSingleTargetSingleVar("QUERY", queryList, "cdws21.ificlaims.com")
                .setResponseContext(returnMap)
                .execute((res, responseContext) -> {
                    String resourcePath = res.getRequest().getResourcePath();
                    String keyword = resourcePath.substring(resourcePath.lastIndexOf('=') + 1);
                    returnMap.put(keyword, res.getResponseContent());

                });`


When I look in the output , it keeps giving me the output from the last run task at a fixed interval. Is there a way to pause the task handling or is it that the Actors are running and waiting for the next task to be processed ?

**Comment by jeffpeiyt** [comment]
@harjitdotsingh  it should only execute each api once. Could you call http://www.parallec.io/javadoc/io/parallec/core/ParallelTask.html#prettyPrintInfo--  on the paralleltask to see the output?  Also can you first reduce the query list to a single one and remove the async() mode so that you can quickly debug?

**Comment by harjitdotsingh** [comment]
The issue isn't happening now. I don't why it kept sending the same request again and again at a fixed interval. It may have been a one off. I will keep an eye out. I think we can close it now

**Comment by jeffpeiyt** [comment]
Cool. Let me know if it happens again.
