### ISSUE TITLE
Which parameter is to control the NettyAsyncHttpProvider?

### ISSUE THREAD

**Issue by shaoxt** [eBay/parallec#74]
I got this exception,  but none of the following options is for this timeout.
new ParallelTaskConfig();
            fastConfig.setActorMaxOperationTimeoutSec(ServiceCallTimeout.CHECK_TIMEOUT/1000);
            fastConfig.setTimeoutInManagerSec(120);
            fastConfig.setTimeoutAskManagerSec(140);

java.util.concurrent.TimeoutException: No response received after 14000 :java.util.concurrent.TimeoutException: No response received after 14000 at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$ReaperFuture.run(NettyAsyncHttpProvider.java:1922) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.ru...

**Comment by jeffpeiyt** [comment]
@shaoxt  could you please check http://www.parallec.io/docs/configurations/#timeout and try `ParallecGlobalConfig.ningFastClientRequestTimeoutMillis = 15000;` :-)

**Comment by shaoxt** [comment]
Thanks a lot.  Trying...  I am changing all the cronus agent API call to use parallec.io

**Comment by jeffpeiyt** [comment]
@shaoxt  awesome!  Thanks.  you can use your own ning client and set its own timeout etc.  Happy Thanksgiving!!
