### ISSUE TITLE
NPE in ChunkedWriteHandler

### ISSUE THREAD

**Issue by shaoxt** [eBay/parallec#75]
java.lang.NullPointerException :java.lang.NullPointerException at org.jboss.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:185) at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:144) at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:554) at org.jboss.netty.handler.codec.replay.ReplayingDecoder.channelClosed(ReplayingDecoder.java:455) at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:77) at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:344) at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:232) at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:404) at org.jboss.netty.channel..

**Comment by shaoxt** [comment]
It might related the old version of netty introduced by async-http-client.
Excluding it.

**Comment by jeffpeiyt** [comment]
@shaoxt When does it happen? Have not observed that before.

**Comment by jeffpeiyt** [comment]
Close it as there is no more activity on it
