### ISSUE TITLE
How to deal with large data flow output based ssh

### ISSUE THREAD

**Issue by icanfly** [eBay/parallec#8]
If you want to output is completed, may have memory overflow, hoping to provide a way to handle the output stream

**Comment by jeffpeiyt** [comment]
HI icanfly,

Thanks much for your question and interests in Parallec.  By default the response is not saved after the task complete, so there should not a be a problem. Unless your responses on a single task is bigger than the heap size

**Comment by jeffpeiyt** [comment]
can you try it out and see if it working with your huge output?

**Comment by icanfly** [comment]
Thanks much for your reply.
Okay, I admit that my goal is to return to a steady stream of data, such as the log flow, and perhaps my purpose is not the framework should be done.

**Comment by jeffpeiyt** [comment]
sure. not a problem. have you considered using log stash etc for this?
